development:
  adapter: postgresql
  encoding: unicode
  database: basicsoa_http_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: basicsoa_http_development
  pool: 5
  username: postgres
